version: '3.8'

services:
  backend:
    image: treeway-dev-backend:latest
    container_name: treeway-dev-backend
    ports:
      - 8081:8080
    networks:
      - treeway-network

  frontend:
    image: treeway-dev-frontend:latest
    container_name: treeway-dev-frontend
    ports:
      - 3001:80
    networks:
      - treeway-network

networks:
  treeway-network:
    driver: bridge
