version: '3.8'

services:
  backend:
    image: treeway-dev-backend:latest
    container_name: treeway-dev-backend
    ports:
      - 8081:8080
    environment:
<<<<<<< HEAD
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
=======
      - TZ=Asia/Seoul  # 시간대 설정 추가
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 호스트의 시간대를 컨테이너에 공유
>>>>>>> 2b529ff (Update docker-compose.yml)
      - /etc/timezone:/etc/timezone:ro
    networks:
      - treeway-network

  frontend:
    image: treeway-dev-frontend:latest
    container_name: treeway-dev-frontend
    ports:
      - 3001:80
    environment:
<<<<<<< HEAD
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
=======
      - TZ=Asia/Seoul  # 시간대 설정 추가
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 호스트의 시간대를 컨테이너에 공유
>>>>>>> 2b529ff (Update docker-compose.yml)
      - /etc/timezone:/etc/timezone:ro
    networks:
      - treeway-network

networks:
  treeway-network:
    driver: bridge
